server:
  port: 9090

spring:
  application:
    name: FLYING-CUBE
  banner:
    location: classpath:banner/banner.txt
  datasource:
    url: jdbc:p6spy:mariadb://localhost:3306/devops?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: devops
    password: new1234@
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate.ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 500
        query:
          in_clause_parameter_padding: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  redis:
    host: 127.0.0.1
    port: 6379
    # password: new1234@

logging:
  config: classpath:logback/logback-spring.xml

fc2:
  jwt:
    secretKey: 123456789012345678901234567890
    expirationDateInMs: 60000 # half hour : 1800000 # 60000 : 1min
    refreshExpirationDateInMs: 3600000 # 3600000 # hour

